name: Build IPK for OpenWrt3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python3

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        tar -xJf openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64 openwrt-sdk

    - name: Update and install feeds
      run: |
        cd openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone luci-app-tinyfilemanager
      run: |
        cd openwrt-sdk/package
        git clone --depth 1 --branch master https://github.com/zero2black/luci-app-tinyfilemanager.git luci-app-tinyfilemanager

    - name: Configure build
      run: |
        cd openwrt-sdk
        make defconfig
        # Select the package LuCI -> Applications -> luci-app-tinyfilemanager
        echo "CONFIG_PACKAGE_luci-app-tinyfilemanager=y" >> .config
        make defconfig

    - name: Compile luci-app-tinyfilemanager
      run: |
        cd openwrt-sdk
        make package/luci-app-tinyfilemanager/compile V=99

    - name: List compiled files
      run: |
        cd openwrt-sdk
        find bin -name "*.ipk"

    - name: Upload IPK package
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-tinyfilemanager
        path: |
          openwrt-sdk/bin/packages/**/luci-app-tinyfilemanager_*.ipk

    - name: Zip packages
      run: |
          #zip -j ${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          #echo -e "**æ–‡ä»¶è¯´æ˜Ž** ðŸŽˆ:\n" >> release.txt
          #echo -e "1. é»˜è®¤ssrä¸Žpasswallçš„æ’ä»¶ä¸Žä¾èµ–æ•´åˆåŒ…\n" >> release.txt
          #echo -e "2. ä½¿ç”¨æ–¹æ³•ï¼šå°†æ•´åˆåŒ…ä¸Šä¼ åˆ°openwrtè®¾å¤‡çš„tmpç›®å½•ï¼Œè¾“å…¥å‘½ä»¤ \`opkg install *.ipk\`\n" >> release.txt
          #echo -e "3. é»˜è®¤åŽ‹ç¼©åŒ…é‡ŒåŒ…å«ssr passwall bypass passwall2 æ’ä»¶\n" >> release.txt
        echo -e "testing" >> release.txt
          
    - name: Upload packages
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.REALESES_TOKEN }}
        artifacts: "openwrt-sdk/bin/packages/**/luci-app-tinyfilemanager_*.ipk"
        #artifacts: "${{ matrix.arch }}-${{ matrix.sdk }}.zip,bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"
        allowUpdates: true
        replacesArtifacts: true
        bodyFile: "release.txt"
        tag: "x86"